Work in progress: Audio recording
nkansal96/aurora-java pull request #6
Opened 2018-04-29 02:41 UTC by jamesbvaughan

This branch adds the ability to record audio for use in the Speech class.

NOTE: **This is not yet finished so do not merge it yet.**

2018-04-29 03:22 UTC, vanshg requested changes

2018-04-29 03:22 UTC, vanshg commented on src/main/java/com/auroraapi/models/Audio.java
> +        System.exit(0);
I don't think we should exit (it'll be unexpected to whatever developer is using the SDK). We should throw an exception instead or return a boolean indicating success or something so the developer can handle the case when there's no audio hardware present

2018-04-29 03:22 UTC, vanshg commented on src/main/java/com/auroraapi/models/Audio.java
> +  public static Audio record(int length, float silence_length) {
camel case is the norm in Java for variable names

2018-04-29 03:22 UTC, vanshg commented on src/main/java/com/auroraapi/models/Speech.java
> +    public static Speech listen(int length, float silence_len) {
camel case here as well

2018-04-29 03:22 UTC, vanshg commented on src/main/java/com/auroraapi/models/Audio.java
> +  static final int NUM_CHANNELS = 1;
Let's also make all the class variables `private`

2018-04-29 03:28 UTC, jamesbvaughan commented on src/main/java/com/auroraapi/models/Audio.java
> +        System.exit(0);
Good call. Half of this was copy/pasted from an example and I didn't really think about all of it.

2018-05-11 03:55 UTC, vanshg approved these changes

2018-05-11 03:56 UTC, vanshg commented
@jamesbvaughan I think this is in a good state now. We can create a separate PR for silence related recording. Go ahead and merge if you think it's good

2018-05-11 04:06 UTC, merged